first_corner: [113,9]
second_corner: [163,-15]
camera_config_file: new_camera_config_style.yml
ptz_config_file: new_ptz_config_style.yml
camera_name: ARB-GVHill
field_of_view: [10.9995, 6.2503]
local_folder: /home/chuong/Data/a_data
max_no_pano_images: 2000
min_free_space: 1000
overlap: 50
pano_end_hour: 18
pano_fallback_folder: /home/pi/Data/Panorama
pano_grid_size: [8, 9]
pano_loop_interval: 60
pano_main_folder: /home/chuong/Data/a_data/Gigavision/chuong_tests
pano_start_hour: 7
pano_start_min: 60
pano_wait_min: 15
remote_folder: /network/phenocam-largedatasets/a_data
remote_storage_address: percy.anu.edu.au
remote_storage_password: ''
remote_storage_username: chuong
scan_order: Cols, right
use_focus_at_center: True
zoom: 800
