1stCorner: 113,9
2ndCorner: 163,-15
CameraConfigFile: ActiCamera.yml
FieldOfView: 10.9995,6.2503
Overlap: 50
PanTiltConfigFile: JSystemsPanTilt.yml
PanoEndHour: 17
PanoGridSize: 8x9
PanoLoopInterval: 60
PanoRootFolder: /home/chuong/Data/a_data/Gigavision/chuong_tests
PanoStartHour: 7
ScanOrder: Cols, right
Zoom: 800
