1stCorner: -151.7770,5.0133
2ndCorner: 11,-25
CameraConfigFile: AxisCamera.yml
CameraName: ARB-GVHill
FieldOfView: 5.6708,3.1613
Focus: 5000
LocalFolder: /home/chuong/Data/a_data
MaxPanoNoImages: 1000000
MinFreeSpace: 1000
Overlap: 40
PanTiltConfigFile: AxisCamera.yml
PanoEndHour: 19
PanoFallbackFolder: /home/pi/Data/Panorama
PanoGridSize: 16x48
PanoLoopInterval: 60
PanoMainFolder: C:\Users\Tim Brown\Documents\ANU\Projects\Gigavision\Gigavision\testpano
PanoStartHour: 7
PanoStartMin: 60
PanoWaitMin: 15
RemoteFolder: /network/phenocam-largedatasets/a_data
RemoteStorageAddress: percy.anu.edu.au
RemoteStoragePassword: ''
RemoteStorageUsername: chuong
ScanOrder: Cols, right
UseFocusAtCenter: True
Zoom: 5000
