1stCorner: 87,0
2ndCorner: 180,-22
CameraConfigFile: AxisCamera.yml
FieldOfView: 4.2570212766,2.3465625
Overlap: 50
PanTiltConfigFile: AxisCamera.yml
PanoEndHour: 18
PanoGridSize: 18x42
PanoLoopInterval: 60
PanoRootFolder: /home/chuong/Data/a_data/Gigavision/chuong_tests
PanoStartHour: 7
PanoStartMin: 60
PanoWaitMin: 15
ScanOrder: Cols, right
Zoom: 8000
