1stCorner: 113,9
2ndCorner: 163,-15
CameraConfigFile: ActiCamera.yml
CameraName: ARB-GVHill
FieldOfView: 10.9995,6.2503
LocalFolder: /home/chuong/Data/a_data
MaxPanoNoImages: 2000
MinFreeSpace: 1000
Overlap: 50
PanTiltConfigFile: JSystemsPanTilt.yml
PanoEndHour: 18
PanoFallbackFolder: /home/pi/Data/Panorama
PanoGridSize: 8x9
PanoLoopInterval: 60
PanoRootFolder: /home/chuong/Data/a_data/Gigavision/chuong_tests
PanoStartHour: 7
PanoStartMin: 60
PanoWaitMin: 15
RemoteFolder: /network/phenocam-largedatasets/a_data
RemoteStorageAddress: percy.anu.edu.au
RemoteStoragePassword: ''
RemoteStorageUsername: chuong
ScanOrder: Cols, right
Zoom: 800
