1stCorner: -151,7.5
2ndCorner: 10,-23
CameraConfigFile: AxisCamera.yml
CameraName: ARB-GVHill
FieldOfView: 4.2570212766,2.3465625
LocalFolder: /home/chuong/Data/a_data
MaxPanoNoImages: 2000
MinFreeSpace: 1000
Overlap: 50
PanTiltConfigFile: AxisCamera.yml
PanoEndHour: 19
PanoFallbackFolder: /home/pi/Data/Panorama
PanoGridSize: 26x76
PanoLoopInterval: 60
PanoMainFolder: $LOCAL_FOLDER/Gigavision/chuong_tests
PanoStartHour: 7
PanoStartMin: 60
PanoWaitMin: 15
RemoteFolder: /network/phenocam-largedatasets/a_data
RemoteStorageAddress: percy.anu.edu.au
RemoteStoragePassword: ''
RemoteStorageUsername: chuong
ScanOrder: Cols, right
UseFocusAtCenter: True
Zoom: 8000
