- set_fact:
    libgphoto2_src: "{{source_dir}}/libgphoto2-{{version or 'latest'}}"
    libgphoto2_build: "{{build_dir}}/libgphoto2"
  no_log: yes

- pacman:
    update_cache: yes
  no_log: yes

- name: Install dependencies for libgphoto2
  pacman:
    name: "{{item}}"
    state: present
  with_items:
    - base-devel
    - libexif
    - libjpeg-turbo

- name: Download libgphoto2-{{version or 'latest'}}
  git:
    repo: https://github.com/gphoto/libgphoto2.git
    clone: yes
    update: yes
    force: yes
    version: "{{version or 'HEAD'}}"
    dest: "{{libgphoto2_src}}"

- file:
    path: "{{libgphoto2_build}}/"
    state: absent
  no_log: yes

- file:
    path: "{{libgphoto2_build}}"
    state: directory
  no_log: yes

- name: Copy gphoto2 to build dir
  command: "rsync -a {{libgphoto2_src}}/ {{libgphoto2_build}}"

- name: Build libgphoto2
  shell: >
    cd "{{libgphoto2_build}}" &&
    autoreconf --install --symlink &&
    ./configure --prefix /usr &&
    make -j2 &&
    make install
  args:
    creates: "/usr/lib/libgphoto2.so"
  no_log: yes
