packages_base:
  - base-devel
  - mlocate
  - nano
  - curl
  - fish
  - git
  - gnupg
  - htop
  - iftop
  - lua-filesystem
  - lua
  - ncdu
  - parallel
  - rsync
  - screen
  - tar
  - tor
  - tree
  - zsh
  - wget
  - python
  - python-pip
  - glances
  - cmake
  - boost
