- include_vars: vars/hostmap.yml

- name: Get cpu serialnumber
  shell: grep -Eor "Serial.*([[:xdigit:]])" /proc/cpuinfo | cut -d " " -f2
  register: check_serial
  check_mode: no
  ignore_errors: yes
  no_log: yes
  changed_when: True

- name: Use machine id
  set_fact:
    hostname: "{{hostnames[ansible_machine_id]|default(inventory_hostname)}}"
    hostname_short: "{{hostnames[ansible_machine_id]|default(inventory_hostname_short)}}"
    when: "{{hostnames[ansible_machine_id]|default(False)}}"

- name: Use cpuid
  set_fact:
    hostname: "{{hostnames[check_serial.stdout]|default(hostname or inventory_hostname)}}"
    hostname_short: "{{hostnames[check_serial.stdout]|default(hostname or inventory_hostname_short)}}"
    when: "{{hostnames[check_serial.stdout]|default(False)}}"

- debug: msg="{{ansible_machine_id}}:{{check_serial.stdout}} using name {{hostname}}"

- name: Set hostname
  hostname: name="{{hostname}}"

- name: Set /etc/hosts
  template:
    src: templates/hosts
    dest: /etc/hosts

- name: Generate locales
  locale_gen:
      name: "{{item}}"
  with_items:
    - en_AU.UTF-8

- name: Set locale
  command: localectl set-locale LANG=en_AU.UTF-8
  no_log: yes

- name: Timezone Australia/Canberra
  timezone: name=Australia/Canberra

- name: Install Sudo
  pacman:
    update_cache: yes
    name: sudo
    state: present
  no_log: yes

- name: Passwordless Sudo
  lineinfile:
    line: "%wheel ALL=(ALL) NOPASSWD: ALL"
    regexp: "^%wheel"
    state: present
    dest: /etc/sudoers
    validate: "visudo -cf %s"

- name: Disable root logins
  file:
    dest: /root/.ssh/authorized_keys
    state: absent

- name: Passwordless Sudo
  lineinfile:
    line: "{{item.line}}"
    regexp: "{{item.regexp}}"
    state: present
    dest: /etc/ssh/sshd_config
  with_items:
    - {line: "PasswordAuthentication no", regexp: "^.*PasswordAuthentication .*"}
    - {line: "PermitRootLogin prohibit-password", regexp: "^.*PermitRootLogin .*"}
