- name: Generate locales
  locale_gen:
      name: "{{item}}"
  with_items:
    - en_AU.UTF-8

- name: Set locale
  command: localectl set-locale LANG=en_AU.UTF-8
  no_log: yes

- name: Timezone Australia/Canberra
  timezone: name=Australia/Canberra

- name: Install Sudo
  pacman:
    update_cache: yes
    name: sudo
    state: present
  no_log: yes

- name: Passwordless Sudo
  lineinfile:
    line: "%wheel ALL=(ALL) NOPASSWD: ALL"
    regexp: "^%wheel"
    state: present
    dest: /etc/sudoers
    validate: "visudo -cf %s"

- name: Disable root logins
  file:
    dest: /root/.ssh/authorized_keys
    state: absent

- name: Passwordless Sudo
  lineinfile:
    line: "{{item.line}}"
    regexp: "{{item.regexp}}"
    state: present
    dest: /etc/ssh/sshd_config
  with_items:
    - {line: "PasswordAuthentication no", regexp: "^.*PasswordAuthentication .*"}
    - {line: "PermitRootLogin prohibit-password", regexp: "^.*PermitRootLogin .*"}
