- include_vars: vars/hostmap.yml

- name: Get cpu serialnumber
  shell: grep -Eor "Serial.*([[:xdigit:]])" /proc/cpuinfo | cut -d " " -f2
  register: check_serial
  check_mode: no
  ignore_errors: yes
  no_log: yes
  changed_when: True

- name: Use machine id
  set_fact:
    hostname: "{{hostnames[ansible_machine_id]|default(inventory_hostname)}}"
    hostname_short: "{{hostnames[ansible_machine_id]|default(inventory_hostname_short)}}"
    when: "{{hostnames[ansible_machine_id]|default(False)}}"

- name: Use cpuid
  set_fact:
    hostname: "{{hostnames[check_serial.stdout]|default(hostname or inventory_hostname)}}"
    hostname_short: "{{hostnames[check_serial.stdout]|default(hostname or inventory_hostname_short)}}"
    when: "{{hostnames[check_serial.stdout]|default(False)}}"

- debug: msg="{{ansible_machine_id}}:{{check_serial.stdout}} using name {{hostname}}"

- name: Set hostname
  hostname: name="{{hostname}}"

- name: Set /etc/hosts
  template:
    src: templates/hosts
    dest: /etc/hosts