name: ARB-GV-ANU-FOREST-C01

first_corner: [200,-14]
second_corner: [150,14]

camera_fov: [15.02, 8.5]
overlap: 50
scan_order: cols,right

interval: 3600
starttime: 0500
stoptime: 1900

output_dir: /home/images/upload/ARB-GV-ANU-FOREST-C01

camera: DSLR

ptz:
  ip: '192.168.1.105:81'
  username: admin
  password: admin
  HTTP_login: "USER={user}&PWD={password}"
  format_url: "http://{ip}{command}&{HTTP_login}"
  return_parser: xml
  pan_range: [71, 355]
  tilt_range: [-89, 29]
  scale: 10.0
  urls:
    set_pan_tilt: "/Bump.xml?GoToP={pan}&GoToT={tilt}"
    get_pan_tilt: "/CP_Update.xml"
  keys:
    get_pan_tilt: [PanPos, TiltPos]

upload:
  enabled: True
  host: sftp.traitcapture.org
  server_dir: /phenocams/gigavision
  username: picam
  password: from_key
