ip: '192.168.1.7'
username: admin
password: 'admin'
HTTP_login: "{user}:{password}" # a ':' character implies basic auth
format_url: "http://{HTTP_login}@{ip}{command}"

image_size_list:
 - [640,480]
 - [800,600]
 - [1024,768]
 - [1280,1024]
 - [1600,1200]
 - [1920,1376]
 - [2560,1920]
 - [3072,2304]
 - [3648,2752]
 - [1024,576]
 - [2048,1152]
 - [3072,1728]
 - [1280,720]
 - [1920,1080]
 - [1920,1080]
 - [2560,1440]
 - [512,672]
 - [1024,1344]
 - [2048,2688]
 - [1600,720]
 - [2560,1152]
 - [3680,1648]
 - [2752,2752]
 - [688,480]

URL_set_image_size: "/admin.cgi?image&resolution={width}x{height}"
URL_get_image: "/jpeg.cgi"
URL_get_image_size: "/admin.cgi?image&_!resolution"
URL_get_video: "/cgi-bin/encoder?GET_STREAM&VIDEO_FPS_NUM=2"
RET_get_image: RAW_JPG ## need to parse binary JPG data like:
                      # stream = urllib.urlopen(URL_GetImage)
                      # byte_array = io.BytesIO(stream.read())
                      # Image = np.array(PIL.Image.open(byte_array))
RET_set_image_size: 'OK: VIDEO_RESOLUTION=''N{}x{}'''
RET_set_zoom: 'OK: OK: ZOOM=''DIRECT,{}'''
RET_set_focus: 'OK: FOCUS=''DIRECT,{}'''
RET_get_image_size: 'VIDEO_RESOLUTION=''N{}x{}'''
RET_get_zoom: 'ZOOM_POSITION=''{}'''
RET_get_focus: 'FOCUS_POSITION=''{}'''

